# Generated by Django 2.2.3 on 2019-11-28 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.BooleanField()),
                ('size', models.DecimalField(decimal_places=2, max_digits=2)),
                ('photo', models.TextField(max_length=50)),
                ('breed', models.CharField(choices=[('BTR', 'Boston Terrier'), ('BOX', 'Boxer'), ('CHW', 'ChowChow'), ('PUG', 'Pug')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('address', models.TextField(max_length=60)),
                ('phone', models.TextField(max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adoption_date', models.DateTimeField(auto_now=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Dogs.Dog')),
                ('shelter_owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shelter_owner', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adoption_date', models.DateTimeField(auto_now=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Dogs.Dog')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Dogs.Shelter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
